apiVersion: #{spc-api-version}#
kind: SecretProviderClass
metadata:
  name: #{spc-binding-couchdb}#
  namespace: #{namespace}#-#{env}#
spec:
  provider: aws
  parameters:
    objects: | 
      - objectName: "#{sm-secret-name-couchdb}#"
        objectType: "secretsmanager"
        objectAlias: "#{name-binding-couchdb}#"

---
apiVersion: #{spc-api-version}#
kind: SecretProviderClass
metadata:
  name: #{spc-binding-itc}#
  namespace: #{namespace}#-#{env}#
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "#{sm-secret-name-itc}#"
        objectType: "secretsmanager"
        objectAlias: "#{name-binding-itc}#"

---
apiVersion: #{spc-api-version}#
kind: SecretProviderClass
metadata:
  name: #{spc-binding-rabbitmq}#
  namespace: #{namespace}#-#{env}#
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "#{sm-secret-name-rabbitmq}#"
        objectType: "secretsmanager"
        objectAlias: "#{name-binding-rabbitmq}#"

---
apiVersion: #{spc-api-version}#
kind: SecretProviderClass
metadata:
  name: #{spc-binding-postgresql}#
  namespace: #{namespace}#-#{env}#
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "#{sm-secret-name-aurorasql}#"
        objectType: "secretsmanager"
        objectAlias: "#{name-binding-postgresql}#"