name: CI Pipeline
on:
  push:
    branches:
      - tunk
    paths:
      - 'Clientes/**'
      - 'Transaciones/**'
      - '**/**'

  pull_request:
    branches:
      - tunk
    paths:
      - 'Clientes/**'
      - 'Transaciones/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - Clientes
          - Transaciones

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Ensure Gradlew is Executable
      run: chmod +x ${{ matrix.service }}/gradlew

    - name: Build Service with Gradle
      run: ${{ matrix.service }}/gradlew clean build -p ${{ matrix.service }}

    - name: Run Unit Tests
      run: ${{ matrix.service }}/gradlew test -p ${{ matrix.service }}

    - name: Build Docker Image
      run: |
        docker build -t $DOCKER_USERNAME/${{ matrix.service,, }}:latest ${{ matrix.service }}
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image to Docker Hub
      run: |
        echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
        docker push $DOCKER_USERNAME/${{ matrix.service }}:latest
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
